<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>streamdeck_totalmix</RootNamespace>
    <AssemblyName>de.shells.totalmix</AssemblyName>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Product>streamdeck-totalmix</Product>
    <AssemblyTitle>streamdeck-totalmix</AssemblyTitle>
    <Copyright>Copyright © Dominik Werland 2022</Copyright>
    <Version>3.3.5</Version>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="streamdeck-totalmix.Tests/**" />
    <None Remove="streamdeck-totalmix.Tests/**" />
    <Content Remove="streamdeck-totalmix.Tests/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RtMidi.Core" Version="1.0.53" />
    <PackageReference Include="Rug.Osc.Core" Version="1.0.0" />
    <PackageReference Include="StreamDeck-Tools" Version="7.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="manifest.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Images/**/*.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="previews/**/*.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="PropertyInspector/**/*.*" Exclude="PropertyInspector/**/.gitattributes" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
